---
title: "Impact of COVID-19 on Worldwide Aviation"
author: "Hao Jin"
date: \today
output:
  html_document:
    code_folding: show
    df_print: paged
    highlight: haddock
    theme: readable
    tidy: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
subtitle: "Section IV - Modeling Result"
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo    = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "")
```

```{r}
library(forecast)       
library(zoo)           
library(xts)         
library(fpp2)         
library(tis)            
library(tseries)        
library(lubridate)      
library(vars)           # VAR
library(urca)
library(AER)
library(tidyverse)
library(fabletools)
library(tsibble)
opensky <- read_csv("flights.csv")
US_daily_covid_cum <- read_csv("US_cumulative.csv")
XAL <- read_csv("^XAL.csv")
```





\newpage

# Preparation 

```{r,echo=FALSE}
# aDF
aDF.test<-function (x, kind = 3, k = trunc((length(x)- 1)^(1/3))) 
{

#kind = the kind of test undertaken
#kind = 1 ==> No constant no trend
#kind = 2 ==> Constant
#kind = 3 ==> Constant and trend

#the null is ALWAYS non stationarity

    if (NCOL(x) > 1) 
        stop("x is not a vector or univariate time series")

    if (any(is.na(x))) 
        stop("NAs in x")

    if (k < 0) 
        stop("k negative")

    DNAME <- deparse(substitute(x))

    k <- k + 1
    y <- diff(x)
    n <- length(y)
    z <- embed(y, k)
    yt <- z[,1]
    xt1 <- x[k:n]
    tt <- k:n

    if (kind == 1)
    {
    table <- cbind(c(2.66, 2.62, 2.6, 2.58, 2.58, 2.58), c(2.26, 
        2.25, 2.24, 2.23, 2.23, 2.23), c(1.95, 1.95, 1.95, 1.95, 
        1.95, 1.95), c(1.60, 1.61, 1.61, 1.62, 1.62, 1.62), c(0.92, 
        0.91, 0.90, 0.89, 0.89, 0.89), c(1.33, 1.31, 1.29, 1.29, 
        1.28, 1.28), c(1.70, 1.66, 1.64, 1.63, 1.62, 1.62), c(2.16, 
        2.08, 2.03, 2.01, 2.00, 2.00))

    if (k > 1) 
    {
        yt1 <- z[,2:k]
        res <- lm(yt ~ xt1 - 1 + yt1)
    }
    else res <- lm(yt ~ xt1 - 1)
    res.sum <- summary(res)
    STAT <- res.sum$coefficients[1,1]/res.sum$coefficients[1,2]
    
    }

    if (kind == 2)
    {
    table <- cbind(c(3.75, 3.58, 3.51, 3.46, 3.44, 3.43), c(3.33, 
        3.22, 3.17, 3.14, 3.13, 3.12), c(3.00, 2.93, 2.89, 2.88, 
        2.87, 2.86), c(2.62, 2.60, 2.58, 2.57, 2.57, 2.57), c(0.37, 
        0.40, 0.42, 0.42, 0.43, 0.44), c(0.00, 0.03, 0.05, 0.06, 
        0.07, 0.07), c(0.34, 0.29, 0.26, 0.24, 0.24, 0.23), c(0.72, 
        0.66, 0.63, 0.62, 0.61, 0.60))

    if (k > 1) 
    {
        yt1 <- z[,2:k]
        res <- lm(yt ~ xt1 + 1 + yt1)
    }
    else res <- lm(yt ~ xt1 + 1)
    res.sum <- summary(res)
    STAT <- res.sum$coefficients[2,1]/res.sum$coefficients[2,2]

    }

    if (kind == 3)
    {
    table <- cbind(c(4.38, 4.15, 4.04, 3.99, 3.98, 3.96), c(3.95, 
        3.8, 3.73, 3.69, 3.68, 3.66), c(3.6, 3.5, 3.45, 3.43, 
        3.42, 3.41), c(3.24, 3.18, 3.15, 3.13, 3.13, 3.12), c(1.14, 
        1.19, 1.22, 1.23, 1.24, 1.25), c(0.8, 0.87, 0.9, 0.92, 
        0.93, 0.94), c(0.5, 0.58, 0.62, 0.64, 0.65, 0.66), c(0.15, 
        0.24, 0.28, 0.31, 0.32, 0.33))

    if (k > 1) 
    {
        yt1 <- z[,2:k]
        res <- lm(yt ~ xt1 + 1 + tt + yt1)
    }
    else res <- lm(yt ~ xt1 + 1 + tt)
    res.sum <- summary(res)
    STAT <- res.sum$coefficients[2,1]/res.sum$coefficients[2,2]

    }

    table <- -table
    tablen <- dim(table)[2]
    tableT <- c(25, 50, 100, 250, 500, 1e+05)
    tablep <- c(0.01, 0.025, 0.05, 0.1, 0.9, 0.95, 0.975, 0.99)
    tableipl <- numeric(tablen)

    for (i in (1:tablen)) tableipl[i] <- approx(tableT, table[,i], n,
rule = 2)$y
    interpol <- approx(tableipl, tablep, STAT, rule = 2)$y

    if (is.na(approx(tableipl, tablep, STAT, rule = 1)$y)) 
        if (interpol == min(tablep)) 
            warning("p-value smaller than printed p-value")
        else warning("p-value greater than printed p-value")

    PVAL <- interpol

    PARAMETER <- k - 1
    METHOD <- "Augmented Dickey-Fuller Test"
    names(STAT) <- "Dickey-Fuller"
    names(PARAMETER) <- "Lag order"

    structure(list(statistic = STAT, parameter = PARAMETER,alternative =
"The series is stationary",
    p.value = PVAL, method = METHOD, data.name = DNAME), class = "htest")
}
```

```{r}
# Daily number of flights in the US (total: domestic + international), create xts object 
US_daily_total <- opensky %>% 
  filter(country == "United States of America") %>% 
  select(day, total_flights)

US_daily_total$day <- as.Date(US_daily_total$day)
US_daily_total_xts <- xts(US_daily_total$total_flights, US_daily_total$day)
```

```{r}
# Daily number of flights in the US (total: domestic + international), create ts object 
US_daily_total <- opensky %>% 
  filter(country == "United States of America") %>% 
  select(day, total_flights)

US_daily_total_ts <- ts(US_daily_total$total_flights, start = c(2019, 1), frequency = 365)
```

```{r}
# US daily, plot, acf, pacf, adf test
US_daily_total_ts %>%
  autoplot() + 
  xlab("Time") + 
  ylab("Number of Flights") + 
  ggtitle("US Daily Flights (Total)")

# tiff("us_ts_display.tiff", units="in", width=6, height=4, res=300)
# png(file="us_ts_display.png", width = 1000, height = 600)
US_daily_total_ts %>%
  ggtsdisplay(main = "US Daily Flights (Total)", theme = theme_bw(base_size = 10))
# dev.off()

# tiff("us_fd_ts_display.tiff", units="in", width=6, height=4, res=300)
diff(US_daily_total_ts) %>%
  ggtsdisplay(main = "US Daily Flights (Total) - First Difference", theme = theme_bw(base_size = 10))
# dev.off()

# Augmented Dickey-Fuller Test
aDF.test(US_daily_total_ts)
aDF.test(diff(US_daily_total_ts), kind = 2)
```

```{r}
# US weekly, plot, acf, pacf, adf test

# Get weekly data
US_weekly_total_xts <- apply.weekly(US_daily_total_xts, sum)
US_weekly_total_ts <- ts(US_weekly_total_xts, start = c(2019,1), frequency = 52)

US_weekly_total_ts %>%
  autoplot() + 
  xlab("Time") + 
  ylab("Number of Flights") + 
  ggtitle("US Weekly Flights (Total)")

tiff("us_wk_ts_display.tiff", units="in", width=6, height=4, res=300)
US_weekly_total_ts %>% 
  ggtsdisplay(main = "US Weekly Flights (Total)", theme = theme_bw(base_size = 10))
dev.off()

tiff("us_wk_fd_ts_display.tiff", units="in", width=6, height=4, res=300)
diff(US_weekly_total_ts) %>% 
  ggtsdisplay(main = "US Weekly Flights (Total) - First Difference", theme = theme_bw(base_size = 10))
dev.off()

# Augmented Dickey-Fuller Test
aDF.test(US_weekly_total_ts)
aDF.test(diff(US_weekly_total_ts))
# US_weekly_ts %>% autoplot()
```






\newpage

# ARIMA

```{r}
# US daily, ARIMA model
US_daily_total_auto_arima <- auto.arima(US_daily_total_ts, ic = "bic")
US_daily_total_auto_arima_forecast <- forecast(US_daily_total_auto_arima, h = 60)

clrs <- c("black", "steelblue2", "blueviolet")

# tiff("us_daily_arima.tiff", units="in", width=6, height=3.5, res=300)
autoplot(US_daily_total_auto_arima_forecast) +
  autolayer(US_daily_total_ts, series = 'Data') +
  autolayer(fitted(US_daily_total_auto_arima), series='Fitted') + 
  autolayer(US_daily_total_auto_arima_forecast$mean, series="Forecast") +
  xlab("Time") +
  ylab("Number of Flights") +
  guides(colour=guide_legend(title="series"), 
         fill=guide_legend(title="prediction interval")) +
  scale_color_manual(values=clrs) + 
  ggtitle("US Daily Flights (Total) - Forecasts from ARIMA(4,1,5)") +
  theme(text = element_text(size = 10))
# dev.off()

# tiff("us_daily_arima_res.tiff", units="in", width=6, height=4, res=300)
US_daily_total_auto_arima$residuals %>%
  ggtsdisplay(main = "US Daily Flights (Total) - ARIMA(4,1,5) Residuals", theme = theme_bw(base_size = 10))
# dev.off()

Box.test(type = 'Ljung', US_daily_total_auto_arima$residuals)

# plot(US_daily_total_ts, xlab = "Date", ylab = "Number of Flights", main = "US Daily Number of Flights", lwd = 2)
# lines(US_daily_total_auto_arima$fitted, col = "steelblue", lwd = 1, lty = 1)
# plot(US_daily_total_auto_arima$residuals, ylab = "Residuals")
# acf(US_daily_total_auto_arima$residuals, type = "correlation", main = "Autocorrelation", ylab = "ACF")
# acf(US_daily_total_auto_arima$residuals, type = "partial", main = "Partial Autocorrelation", ylab = "PACF")

# plot(forecast(US_daily_total_auto_arima, h = 30))
# plot(forecast(US_daily_total_auto_arima, h = 30), xlim = c(2021.5, 2022.1), shadecols = "oldstyle")
```

```{r}
# US weekly, ARIMA model
US_weekly_total_auto_arima <- auto.arima(US_weekly_total_ts, ic = "aic")
US_weekly_total_auto_arima_forecast <- forecast(US_weekly_total_auto_arima, h = 8)

# tiff("us_weekly_arima.tiff", units="in", width=6, height=3.5, res=300)
autoplot(US_weekly_total_auto_arima_forecast) +
  autolayer(US_weekly_total_ts, series = "Data") +
  autolayer(fitted(US_weekly_total_auto_arima), series = "Fitted") + 
  autolayer(US_weekly_total_auto_arima_forecast$mean, series = "Forecast") +
  xlab("Time") +
  ylab("Number of Flights") +
  guides(colour = guide_legend(title = "series"), 
         fill = guide_legend(title = "prediction interval")) +
  scale_color_manual(values = clrs) + 
  ggtitle("US Weekly Flights (Total) - Forecasts from ARIMA(1,1,0)") +
  theme(text = element_text(size = 10))
# dev.off()

# tiff("us_weekly_arima_res.tiff", units="in", width=6, height=4, res=300)
US_weekly_total_auto_arima$residuals %>%
  ggtsdisplay(main = "US Weekly Flights (Total) - ARIMA(1,1,0) Residuals", theme = theme_bw(base_size = 10))
# dev.off()

Box.test(type = 'Ljung', US_weekly_total_auto_arima$residuals)
```





\newpage

# Holt Winters

```{r}
# US daily, Holt-Winters model, using (stat::HoltWinters) implementation
US_daily_total_stats_HW_fit <- stats::HoltWinters(US_daily_total_ts)
US_daily_total_stats_HW_forecast <- forecast(US_daily_total_stats_HW_fit, h = 60)

clrs_hw <- c("black", "blueviolet")

# tiff("us_daily_holtwinters.tiff", units="in", width=6, height=3.5, res=300)
US_daily_total_stats_HW_forecast %>%
  autoplot() + 
  autolayer(US_daily_total_ts, series = 'Data') +
  autolayer(US_daily_total_stats_HW_forecast$mean, series="Forecast") +
  xlab("Time") +
  ylab("Number of Flights") +
  guides(colour=guide_legend(title="series"), 
         fill=guide_legend(title="prediction interval")) +
  scale_color_manual(values=clrs_hw) + 
  ggtitle("US Daily Flights (Total) - Forecasts from HoltWinters()") +
  theme(text = element_text(size = 10))
# dev.off()

(US_daily_total_stats_HW_forecast$residuals) %>%
  ggtsdisplay()
```

```{r}
# US weekly, Holt-Winters model, using (stat::HoltWinters) implementation
US_weekly_total_stats_HW_fit <- stats::HoltWinters(US_weekly_total_ts)
US_weekly_total_stats_HW_forecast <- forecast(US_weekly_total_stats_HW_fit, h = 8)

# tiff("us_weekly_holtwinters.tiff", units="in", width=6, height=3.5, res=300)
US_weekly_total_stats_HW_forecast %>%
  autoplot() + 
  autolayer(US_weekly_total_ts, series = 'Data') +
  autolayer(US_weekly_total_stats_HW_forecast$mean, series="Forecast") +
  xlab("Time") +
  ylab("Number of Flights") +
  guides(colour=guide_legend(title="series"), 
         fill=guide_legend(title="prediction interval")) +
  scale_color_manual(values=clrs_hw) + 
  ggtitle("US Weekly Flights (Total) - Forecasts from HoltWinters()") +
  theme(text = element_text(size = 10))
# dev.off()

residuals(US_weekly_total_stats_HW_fit) %>%
  ggtsdisplay()
```

```{r}
# US daily, Holt-Winters model, using (forecast::hw) implementation
US_daily_total_ts_no_time <- ts(US_daily_total$total_flights, frequency = 7)
US_daily_total_ets_hw_fit <- hw(US_daily_total_ts_no_time, damped = F, seasonal = "additive", h = 60)

# tiff("us_daily_ets_hw.tiff", units="in", width=6, height=3.5, res=300)
US_daily_total_ets_hw_fit %>%
  autoplot() + 
  autolayer(US_daily_total_ts_no_time, series = 'Data') +
  autolayer(US_daily_total_ets_hw_fit$fitted, series="Fitted") +
  autolayer(US_daily_total_ets_hw_fit$mean, series="Forecast") +
  xlab("Time") +
  ylab("Number of Flights") +
  guides(colour=guide_legend(title="series"), 
         fill=guide_legend(title="prediction interval")) +
  scale_color_manual(values=clrs) + 
  ggtitle("US Daily Flights (Total) - Forecasts from hw()") +
  theme(text = element_text(size = 10))
# dev.off()

# tiff("us_daily_hw_res.tiff", units="in", width=6, height=4, res=300)
US_daily_total_ets_hw_fit$residuals %>%
  ggtsdisplay(main = "US Daily Flights (Total) - hw() Method Residuals", theme = theme_bw(base_size = 10))
# dev.off()

Box.test(type = 'Ljung', US_daily_total_ets_hw_fit$residuals)
Box.test(type = 'Ljung', US_weekly_total_ts)
```





\newpage

# VAR

```{r}
US_weekly_total_xts_normal <- (US_weekly_total_xts - mean(US_weekly_total_xts)) / sd(US_weekly_total_xts)
US_weekly_total_ts_normal <- ts(US_weekly_total_xts_normal, start = c(2019, 1), frequency = 52)
```

```{r}
# COVID Data
# US_daily_covid_cum_ts <- ts(US_daily_covid_cum$each_day_US)
# US_daily_covid_ts <- ts(US_daily_covid_cum_ts - stats::lag(US_daily_covid_cum_ts, -1), start = c(2020,23), frequency = 365)
# plot(US_daily_covid_ts)

# xts object
# US_daily_covid_date <- as.Date(US_daily_covid_cum$X1[-1], format = "%m/%d/%y")
# US_daily_covid_ts_xts <- xts(as.vector(US_daily_covid_ts), US_daily_covid_date)

# US_weekly_covid_xts <- apply.weekly(US_daily_covid_ts_xts, sum)
# US_weekly_covid_ts <- ts(US_weekly_covid_xts, start = c(2020,4), frequency = 52)
# US_weekly_covid_xts_normal <- (US_weekly_covid_xts - mean(US_weekly_covid_xts)) / sd(US_weekly_covid_xts)
# US_weekly_covid_ts_normal <- ts(US_weekly_covid_xts_normal, start = c(2020,4), frequency = 52)

# df <- cbind(US_weekly_total_ts_normal, US_weekly_covid_ts_normal)
# df <- tseries::na.remove(df)
# autoplot(df) +
#   ylab("Z-Score") +
#   ggtitle("Normalized Number of Flights and Confirmed Cases in the US") + 
#   theme(legend.position="bottom") +
#   scale_x_continuous(breaks = seq(2020, 2022, by = 1)) + 
#   scale_colour_discrete(labels = c("Weekly Number of Flights", "Weekly Confirmed Cases"))
```

```{r}
XAL_ts <- ts(XAL$`Adj Close`, start = c(2019, 1), frequency = 52)
XAL_ts_normal <- (XAL_ts - mean(XAL_ts)) / sd(XAL_ts)

df_us_wk_XAL_ts_normal <- cbind("Flights" = US_weekly_total_ts_normal, "XAL" =  XAL_ts_normal)

# tiff("us_flights_XAL.tiff", units="in", width=6, height=4, res=300)
autoplot(df_us_wk_XAL_ts_normal) +
  ylab("Z-Score") +
  ggtitle("Normalized Weekly Number of Flights in the US and XAL Index") + 
  scale_x_continuous(breaks = seq(2019, 2022, by = 1)) + 
  scale_colour_discrete(labels = c("Flights", "XAL")) +
  theme(text = element_text(size = 10))
# dev.off()
```
```{r}
aDF.test(XAL_ts)
aDF.test(diff(XAL_ts))

# tiff("XAL_fd_tsdisplay.tiff", units="in", width=6, height=4, res=300)
diff(XAL_ts) %>% 
  ggtsdisplay(main = "The XAL Index - First Difference", theme = theme_bw(base_size = 10))
# dev.off()
```

```{r}
# Test for cointegration
aDF.test((XAL_ts_normal - US_weekly_total_ts_normal))
po.test(df_us_wk_XAL_ts_normal) # null hypothesis: not cointegrated
```

```{r}
# VAR model
df_XAL_ts <- cbind("Flights" = US_weekly_total_ts, "XAL" =  XAL_ts)
df_XAL <- data.frame(df_XAL_ts)

VARselect(df_XAL, lag.max = 8)
var_fit = VAR(df_XAL, p = 1)
# summary(var_fit)

var_pred = predict(var_fit, h = 8)
# tiff("var_forecast.tiff", units="in", width=6, height=6, res=300)
plot(var_pred, xlab = "Starting Week 1 of 2020")
# dev.off()
```

```{r}
# Causality
grangertest(US_weekly_total_ts ~ XAL_ts)
grangertest(XAL_ts ~ US_weekly_total_ts)
```

```{r}
irf_model = irf(var_fit, n.ahead = 26)

irf_xal <- irf(var_fit, impulse = "XAL", response = "Flights", n.ahead = 26, ortho = TRUE,
               cumulative = FALSE, boot = TRUE, ci = 0.9, runs = 100)
#png("figs/irf_asy_quarterly.png", width = 700, height = 500)
# tiff("irf_1.tiff", units="in", width=6, height=4, res=300)
plot(irf_xal)
# dev.off()

irf_flights <- irf(var_fit, impulse = "Flights", response = "XAL", n.ahead = 26, ortho = TRUE,
               cumulative = FALSE, boot = TRUE, ci = 0.9, runs = 100)
#png("figs/irf_asy_quarterly.png", width = 700, height = 500)
# tiff("irf_2.tiff", units="in", width=6, height=4, res=300)
plot(irf_flights)
# dev.off()
```






